#!/usr/bin/env python3
from src.executor import execute_from_code


print('Welcome to the repl')

while True:
    code = input('|> ')
    try:
        result = execute_from_code(code)[-1]    # print the last result
        print(result)
    except Exception as e:
        print('ERROR!')
        print(e)
